server:
  port: 8083

twilio:
  accountSid:
  authToken:
  trialNumber:

jwt:
  token:
    validity: 18000
    prefix: Bearer
  signing:
    key: signingkey
  authorities:
    key: roles
  header:
    string: Authorization

appDescription: "z"
appVersion: "1.0.0"
